---

  - name: install packages
    when: (ansible_distribution == "CentOS" or ansible_distribution == "EL")
    yum:
      name:
        - 'nginx'
        - 'php'
        - 'php-mysqlnd'
        - 'php-fpm'
        - 'php-cli'
        - 'php-gd'
        - 'php-json'
        - 'php-mbstring'
        - 'php-mcrypt'
        - 'php-readline'
        - 'php-xml'
        - 'php-zip'
        - 'python-pip'
        - 'mariadb-server'
        - 'mariadb'
        - 'MySQL-python'
        - 'libselinux-python'
        - 'unzip'
        - 'firewalld'
      state: present


    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install caching
    when: (caching == True and or ansible_distribution == "EL" or ansible_distribution == "CentOS")
    yum:
      name: memcached
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "EL" or ansible_distribution == "CentOS")
    yum:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: enable Firewalld
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS")
    service:
      name: firewalld
      state: started
